# Generated by Django 4.1.5 on 2023-05-13 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='')),
                ('portet', models.ImageField(upload_to='')),
                ('gradues', models.CharField(max_length=1000, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=170, verbose_name='')),
                ('logo', models.ImageField(upload_to='', verbose_name='')),
                ('text', models.CharField(max_length=5000, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Plays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=170, verbose_name='')),
                ('date', models.DateTimeField(max_length=170, verbose_name='')),
                ('logo', models.ImageField(upload_to='', verbose_name='')),
                ('duration', models.IntegerField()),
                ('age_limit', models.IntegerField()),
                ('Pushkins_card', models.BooleanField()),
                ('annotation', models.CharField(max_length=2500, verbose_name='')),
                ('stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.employee')),
            ],
        ),
    ]
