# Generated by Django 4.1.5 on 2023-11-25 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Имя сотрудника')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Портрет')),
                ('biography', models.CharField(max_length=1000, null=True, verbose_name='Биография')),
                ('gradues', models.CharField(max_length=1000, verbose_name='Награды')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=170, verbose_name='Название новости')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Постер')),
                ('text', models.CharField(max_length=5000, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Plays',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=170, verbose_name='Название спектакля')),
                ('date', models.DateTimeField(max_length=170, verbose_name='Дата')),
                ('logo', models.ImageField(upload_to='', verbose_name='Постер')),
                ('duration', models.IntegerField(verbose_name='Длительность спектакля (в мин)')),
                ('age_limit', models.IntegerField(verbose_name='Возрастное ограничение')),
                ('Pushkins_card', models.BooleanField(verbose_name='Доступна ли Пушкинская карта')),
                ('annotation', models.CharField(max_length=2500, verbose_name='Аннотация к спектаклю')),
            ],
            options={
                'verbose_name': 'Спектакль',
                'verbose_name_plural': 'Спектакли',
            },
        ),
        migrations.CreateModel(
            name='Employee_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.employee')),
                ('id_plays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.plays')),
            ],
            options={
                'verbose_name': 'Группа сотрудников',
                'verbose_name_plural': 'Группы сотрудников',
            },
        ),
    ]
